# Generated by Django 6.0.2 on 2026-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="观测时间")),
                ("temp_c", models.FloatField(verbose_name="摄氏温度")),
                ("humidity", models.IntegerField(verbose_name="相对湿度(%)")),
                ("wind_speed", models.FloatField(verbose_name="风速(km/h)")),
                ("visibility", models.FloatField(verbose_name="能见度(km)")),
                ("pressure", models.FloatField(verbose_name="气压(kPa)")),
                ("condition", models.CharField(max_length=100, verbose_name="天气状况")),
            ],
        ),
    ]
